language: python
python:
  - "2.7"
addons:
  postgresql: "9.1"
before_script:
  - createdb sugar_db
install:
  - pip install tox
env:
  - TOX_ENV=flake8
  - TOX_ENV=docs
  - TOX_ENV=tests
script:
  - tox -e $TOX_ENV
